layout_spectrum: 0.5085832
typography_spectrum: 0.1344086
color:
  saturation: 0.5197133
  lightness: 0.3548387
  brandStrength: 0
  brandColors:
    - '#160C0C'
    - '#FBE0C7'
    - '#B49180'
    - '#AC6C4B'
    - '#FFFFFF'
  rhythmicContrast: 0.8709677
name: Amy Kim
